"""Add category field to Bug model

Revision ID: 1118ec1bd628
Revises: 
Create Date: 2025-05-07 00:06:54.115869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1118ec1bd628'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bug', schema=None) as batch_op:
        # 1. 先添加可为空的列
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=True))
    
    # 2. 更新所有现有记录的category值为'功能'
    op.execute("UPDATE bug SET category = '功能' WHERE category IS NULL")
    
    # 3. 最后将列改为NOT NULL
    with op.batch_alter_table('bug', schema=None) as batch_op:
        batch_op.alter_column('category', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bug', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###