"""add comment_id to attachment model

Revision ID: af469328761e
Revises: add_user_permissions
Create Date: 2025-05-07 18:37:11.565151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af469328761e'
down_revision = 'add_user_permissions'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_attachment_comment', 'comment', ['comment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comment_id')

    # ### end Alembic commands ###